# Generated by Django 5.2.15 on 2026-07-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(blank=True, help_text='smarthr360-auth user id (lets the employee chat about themselves).', null=True, unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('engagement_score', models.IntegerField(default=100)),
                ('performance_score', models.IntegerField(default=75)),
                ('absence_days_90d', models.PositiveSmallIntegerField(default=0)),
                ('last_evaluation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('identified_need', models.CharField(blank=True, max_length=100, null=True)),
                ('messages', models.JSONField(default=list)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='retention.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending HR Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='retention.conversation')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='retention.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('low_engagement', 'Low Engagement'), ('high_absence', 'High Absence Rate'), ('poor_performance', 'Poor Performance'), ('negative_feedback', 'Negative Feedback')], max_length=50)),
                ('intensity', models.IntegerField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='retention.employee')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='retention.signal'),
        ),
    ]
