# Generated by Django 5.2.15 on 2026-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('low_engagement', 'Low Engagement'), ('high_absence', 'High Absence Rate'), ('poor_performance', 'Poor Performance'), ('negative_feedback', 'Negative Feedback'), ('burnout_risk', 'Burnout Risk (workload)')], max_length=50),
        ),
    ]
