# Generated by Django 5.2.15 on 2026-07-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention', '0002_alter_signal_signal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='employee_retained',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='outcome_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='action',
            name='outcome_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='outcome_recorded_by_user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
